### ISSUE TITLE
Search component bug

### ISSUE THREAD

**Issue by oguzsh** [selimyalinkilic/next-countries#2]
# Problem
- When I type any data that you don't have into your search bar, your app throws an error

## Screenshot :
![image](https://user-images.githubusercontent.com/15168877/142693244-c153c36f-2b60-4bfa-820d-0908f8b069b9.png)

**Comment by selimyalinkilic** [comment]
@oguzsh Added Input value control then filtered data by input value. If data names includes input value then showing countries. If is not includes then showing message. 

You can check again [DEMO](https://next-countries-tawny.vercel.app)
